version: "2"
services:
  db:
    image: postgres:10
    container_name : odoo-db-${SUFFIXE}
    #restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mdpOdoo
      POSTGRES_USER: userOdoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo_data_db:/var/lib/postgresql/data

  odoo:
    image: odoo:12.0
    container_name : odoo-${SUFFIXE}
    #restart: unless-stopped
    links :
      - db
    ports:
      - 9500-9599:8069
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_data_config:/etc/odoo
      - odoo_data_addons:/mnt/extra-addons
    depends_on:
      - db
    environment:
      HOST: db
      PORT: 5432
      USER: userOdoo
      PASSWORD: mdpOdoo

volumes:
  odoo_data_db: {}
  odoo_data: {}
  odoo_data_config: {}
  odoo_data_addons: {}
