version : '2'

services :

  db :
    image : aporaf/mariadb-prestashop-perso:0.1
    container_name : prestashop-db-${SUFFIXE}
    #restart : unless-stopped
    networks:
      - net_e-combox
    expose :
      - "3306"
    environment :
      MYSQL_ROOT_PASSWORD : bdAdmin
      MYSQL_DATABASE : prestashop
      MYSQL_USER : userPS
      MYSQL_PASSWORD : mdpPS
    volumes :
      - prestashop_data_db:/var/lib/mysql

  prestashop :
    image : aporaf/prestashop-perso:0.1
    container_name : prestashop-${SUFFIXE}
    #restart : unless-stopped
    networks:
      - net_e-combox
    ports :
      - "9100-9199:80"
    volumes :
      - prestashop_data:/var/www/html
    external_links:
      - prestashop-db-${SUFFIXE}:db
    environment :
      PS_HANDLE_DYNAMIC_DOMAIN : 1
    depends_on :
      - db

networks:
  net_e-combox:
    external:
      name: bridge_e-combox

volumes :
  prestashop_data_db: {}
  prestashop_data: {}
