version : '2'

services :

  db :
    image : mariadb
    container_name : ps-db-${SUFFIXE}
    restart : always
    expose :
      - "3306"
    environment :
      MYSQL_ROOT_PASSWORD : bdAdmin
      MYSQL_DATABASE : prestashop
      MYSQL_USER : userPS
      MYSQL_PASSWORD : mdpPS
    volumes :
      - db_data_ps:/var/lib/mysql

  prestashop :
    image : prestashop/prestashop
    container_name : prestashop-${SUFFIXE}
    restart : always
    links :
      - db
    ports :
      - "9100-9199:80"
    volumes :
      - ps_data:/var/www/html
    depends_on :
      - db
    environment :
      PS_HANDLE_DYNAMIC_DOMAIN : 1
      PS_FOLDER_ADMIN : administration
      PS_FOLDER_INSTALL : installation
 
volumes :
  db_data_ps: {}
  ps_data: {}
