version: "2"
services:
  db:
    image: aporaf/mariadb10.3
    container_name : mautic-db-${SUFFIXE}
    #restart: unless-stopped
    networks:
      - net_e-combox
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
      MYSQL_DATABASE: mautic
      MYSQL_USER: userMautic
      MYSQL_PASSWORD: mdpMautic
      MYSQL_INITDB_SKIP_TZINFO: 1
      HTTP_PROXY : $HTTP_PROXY
      HTTPS_PROXY : $HTTPS_PROXY
      http_proxy : $http_proxy
      https_proxy : $https_proxy
      no_proxy : $no_proxy
      NO_PROXY : $NO_PROXY
    volumes:
      - mautic_data_db:/var/lib/mysql

  mautic:
    image: mautic/mautic
    container_name : mautic-${SUFFIXE}
    #restart: unless-stopped
    networks:
      - net_e-combox
    ports:
      - 9300-9399:80
    volumes:
      - mautic_data:/var/www/html
    external_links:
      - mautic-db-${SUFFIXE}:db
    depends_on:
      - db
    environment:
      MAUTIC_DB_HOST: db:3306
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_USER: userMautic
      MAUTIC_DB_PASSWORD: mdpMautic
      MAUTIC_VERSION: 2.15.1
      HTTP_PROXY : $HTTP_PROXY
      HTTPS_PROXY : $HTTPS_PROXY
      http_proxy : $http_proxy
      https_proxy : $https_proxy
      no_proxy : $no_proxy
      NO_PROXY : $NO_PROXY

networks:
  net_e-combox:
    external:
      name: bridge_e-combox

volumes:
  mautic_data_db: {}
  mautic_data: {}
