version: "2"
services:
  db:
    image: aporaf/mariadb-woocommerce-perso:latest
    container_name : woocommerce-db-${SUFFIXE}
    #restart: unless-stopped
    networks:
      - net_e-combox
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: userWP
      MYSQL_PASSWORD: mdpWP    
    volumes:
      - woocommerce_data_db:/var/lib/mysql

  wordpress:
    image: aporaf/woocommerce-perso-avec-wp-cli:latest
    container_name : woocommerce-${SUFFIXE}
    #restart: unless-stopped
    networks:
      - net_e-combox
    ports:
      - 9200-9299:80
    volumes:
      - woocommerce_data:/var/www/html
    external_links:
      - woocommerce-db-${SUFFIXE}:db
    depends_on:
      - db

networks:
  net_e-combox:
    external:
      name: bridge_e-combox

volumes:
  woocommerce_data_db: {}
  woocommerce_data: {}
