version: "2"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${NOMSTACK}
    #restart: unless-stopped
    ports:
      - 8770-8799:80
    external_links:
      - ${NOMCONTENEUR_DB}:db
    networks: 
      - default
    environment :
      - PMA_USER=userOdoo 
      - PMA_PASSWORD=mdpOdoo
      - PMA_HOST=db

networks:
  default:
    external:
      name: ${NOMSTACK}_default 
      


 
