version: "2"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${NOMSTACK}
    #restart: unless-stopped
    networks:
      - net_e-combox
    ports:
      - 8740-8769:80
    external_links:
      - ${NOMCONTENEUR_DB}:db
    environment :
      - PMA_USER=userWP 
      - PMA_PASSWORD=mdpWP
      - PMA_HOST=db
      HTTP_PROXY : $HTTP_PROXY
      HTTPS_PROXY : $HTTPS_PROXY
      http_proxy : $http_proxy
      https_proxy : $https_proxy
      no_proxy : $no_proxy
      NO_PROXY : $NO_PROXY

networks:
  net_e-combox:
    external:
      name: bridge_e-combox 
      


 
