version : '2'

services :

  db :
    image : aporaf/mariadb-prestashop-vierge:0.4
    container_name : prestashop-db-${SUFFIXE}
    #restart : unless-stopped
    networks:
      - net_e-combox
    expose :
      - "3306"
    environment :
      MYSQL_ROOT_PASSWORD : bdAdmin
      MYSQL_DATABASE : prestashop
      MYSQL_USER : userPS
      MYSQL_PASSWORD : mdpPS
      #TZ: Europe/Paris
      MYSQL_INITDB_SKIP_TZINFO : 1
      HTTP_PROXY : $HTTP_PROXY
      HTTPS_PROXY : $HTTPS_PROXY
      http_proxy : $http_proxy
      https_proxy : $https_proxy
      no_proxy : $no_proxy
      NO_PROXY : $NO_PROXY
    volumes :
      - prestashop_data_db:/var/lib/mysql

  prestashop :
    image : aporaf/prestashop-vierge:0.4
    container_name : prestashop-${SUFFIXE}
    #restart : unless-stopped
    networks:
      - net_e-combox
    ports :
      - "9100-9199:80"
    volumes :
      - prestashop_data:/var/www/html  
    external_links:
      - prestashop-db-${SUFFIXE}:db
    environment :
      HTTP_PROXY : $HTTP_PROXY
      HTTPS_PROXY : $HTTPS_PROXY
      http_proxy : $http_proxy
      https_proxy : $https_proxy
      no_proxy : $no_proxy
      NO_PROXY : $NO_PROXY
    depends_on :
      - db
 
networks:
  net_e-combox:
    external:
      name: bridge_e-combox

volumes :
  prestashop_data_db: {}
  prestashop_data: {}
