version: "2"
services:
  db:
    image: aporaf/mariadb-woocommerce:latest
    container_name : woocommerce-db-${SUFFIXE}
    restart: always
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin      
    volumes:
      - woocommerce_data_db:/var/lib/mysql

  wordpress:
    image: aporaf/woocommerce-avec-wp-cli:latest
    container_name : woocommerce-${SUFFIXE}
    restart: always
    ports:
      - 9200-9299:80
    volumes:
      - woocommerce_data:/var/www/html
    depends_on:
      - db

volumes:
  woocommerce_data_db: {}
  woocommerce_data: {}
