version: "2"
services:
  db:
    image: bitnami/mariadb:latest
    container_name : suitecrm-db-${SUFFIXE}
    restart: unless-stopped
    expose :
      - "3306"
    volumes:
      - suitecrm_data_db:/bitnami
    environment:
      MARIADB_ROOT_PASSWORD: bdAdmin
      MARIADB_DATABASE: suitecrm
      MARIADB_USER: userSuiteCRM
      MARIADB_PASSWORD: mdpSuiteCRM
    

  suitecrm:
    image: bitnami/suitecrm:latest
    container_name : suitecrm-${SUFFIXE}
    restart: unless-stopped
    ports:
      - 9400-9499:80
    volumes:
      - suitecrm_data:/bitnami
    depends_on:
      - db
    environment:
      MARIADB_HOST: db
      MARIADB_PORT_NUMBER: 3306
      SUITECRM_DATABASE_NAME: suitecrm
      SUITECRM_DATABASE_USER: userSuiteCRM
      SUITECRM_DATABASE_PASSWORD: mdpSuiteCRM
      SUITECRM_USERNAME: adminSCRM
      SUITECRM_PASSWORD: scrmAdmin0
      SUITECRM_EMAIL: admin@btsmco.fr
      

volumes:
  suitecrm_data_db: {}
  suitecrm_data: {}
