version: "2"
services:
  db:
    image: mariadb:10.4
    container_name : mautic-db-${SUFFIXE}
    restart: unless-stopped
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
      MYSQL_DATABASE: mautic
      MYSQL_USER: userMautic
      MYSQL_PASSWORD: mdpMautic
    volumes:
      - mautic_data_db:/var/lib/mysql

  wordpress:
    image: mautic/mautic
    container_name : mautic-${SUFFIXE}
    restart: unless-stopped
    ports:
      - 9300-9399:80
    volumes:
      - mautic_data:/var/www/html
    depends_on:
      - db
    environment:
      MAUTIC_DB_HOST: db:3306
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_USER: userMautic
      MAUTIC_DB_PASSWORD: mdpMautic

volumes:
  mautic_data_db: {}
  mautic_data: {}
