version: "2"
services:
  db:
    image: aporaf/mariadb-blog:latest
    container_name : blog-db-${SUFFIXE}
    #restart: unless-stopped
    expose :
      - "3306"
    networks:
      - net_e-combox
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: userWP
      MYSQL_PASSWORD: mdpWP
    volumes:
      - blog_data_db:/var/lib/mysql

  wordpress:
    image: aporaf/blog-avec-wp-cli:latest
    container_name : blog-${SUFFIXE}
    #restart: unless-stopped
    ports:
      - 9200-9299:80
    networks:
      - net_e-combox
    volumes:
      - blog_data:/var/www/html
    depends_on:
      - db

networks:
  net_e-combox:
    external:
      name: bridge_e-combox

volumes:
  blog_data_db: {}
  blog_data: {}
