version: "2"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${NOMSTACK}
    #restart: unless-stopped
    networks:
      - net_e-combox
    ports:
      - 8770-8799:80
    external_links:
      - ${NOMCONTENEUR_DB}:db
    environment :
      - PMA_USER=userOdoo 
      - PMA_PASSWORD=mdpOdoo
      - PMA_HOST=db

networks:
  net_e-combox:
    external:
      name: bridge_e-combox
      


 
