version : '2'

services :

  servbd :
    image : mariadb
    container_name : ps-bd
    restart : always
    expose :
      - "3306"
    environment :
      MYSQL_ROOT_PASSWORD : bdAdmin
      MYSQL_DATABASE : prestashop
      MYSQL_USER : userPS
      MYSQL_PASSWORD : mdpPS
    volumes :
      - data_bd:/var/lib/mysql

  prestashop :
    image : prestashop/prestashop
    container_name : prestashop
    restart : always
    links :
      - servbd
    ports :
      - "9301-9305:80"
    volumes :
      - data_ps:/var/www/html
    depends_on :
      - servbd
    environment :
      DB_SERVER : servbd
      DB_NAME : prestashop
      DB_USER : root
      DB_PASSWD : bdAdmin
      DB_PREFIX : ps_
      PS_LANGUAGES : fr
      PS_LANGUAGE : fr
      PS_COUNTRY : FR
      PS_INSTALL_AUTO : 1
      PS_HANDLE_DYNAMIC_DOMAIN : 1
      PS_FOLDER_ADMIN : administration
      PS_FOLDER_INSTALL : installation

volumes :
  data_bd: {}
  data_ps: {}
